# Generated by Django 4.0.3 on 2022-04-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name_plural': 'Livros'},
        ),
    ]
